apps/predictor/urls.py
from django.conf.urls import url
from . import views

app_name = "predictor"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^new$', views.new, name="new"),
    url(r'^create$', views.create, name="create"),
    url(r'^show$', views.show, name="show"),
]

apps/user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^new$', views.new, name="new"),
    url(r'^create$', views.create, name="create"),
    url(r'^logins$', views.logins, name="logins"),
    url(r'^logouts$', views.logouts, name="logouts"),
]

learning/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="predictor/")),
    url(r'user/', include('apps.user.urls', namespace="user")),
    url(r'predictor/', include('apps.predictor.urls', namespace="predictor")),
]

apps/predictor/models.py
from django.db import models

# Create your models here.

apps/user/models.py
from django.db import models 
from django.contrib.auth.models import AbstractUser, User

# Create your models here.

apps/predictor/forms.py
from django import forms

LEARN_FORM_CHOICES = [
    (',', 'Comma'),
    ('\t', 'Tab'),
    (';', 'Semi-colon'),
]
class LearnForm(forms.Form):
    name = forms.CharField(max_length=120)
    first = forms.CharField(max_length=120)
    second = forms.CharField(max_length=120)
    third = forms.CharField(max_length=120)
    size = forms.FloatField()
    file = forms.FileField()    
    separator = forms.ChoiceField(choices = LEARN_FORM_CHOICES)  
    def __init__(self, *args, **kwargs):
        super(LearnForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'example.csv'})
        self.fields['first'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder':'first'})
        self.fields['second'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder':'second'})
        self.fields['third'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder':'third'})
        self.fields['size'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder':'float int'})
        

apps/user/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
        "first_name", 
        "last_name",
        "username",
        "email",
        "password1",
        "password2"
        ]
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
        self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Confirm'})

class LoginForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1"]
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'})

apps/predictor/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import LearnForm
from .predictor import predictor

# Create your views here.
@login_required(login_url="/user/")
def index(request):
    return render(request, "predictor/index.html")

@login_required(login_url="/user/")
def new(request):
    form = LearnForm()
    return render(request, "predictor/new.html", {'form': form})

@login_required(login_url="/user/")
def create(request):
    if request.method == "POST":
        form = LearnForm(request.POST, request.FILES)
        
        if form.is_valid():
            prediction = predictor(request.FILES['file'], request.POST['first'], request.POST['second'], request.POST['third'], request.POST['size'], request.POST['separator'])
            return show(request, prediction)
            
    return redirect(reverse("predictor:new")) 

@login_required(login_url="/user/")
def show(request, data):
    info = {
        "name": request.POST['name'],
        "size": request.POST['size'],
        "first": request.POST['first'],
        "second": request.POST['second'],
        "third": request.POST['third'],
        "separator": request.POST['separator']
    }
    print(request.POST)
    return render(request, "predictor/show.html", {'data': data, 'info': info})

apps/user/views.py
from django.shortcuts import render, reverse, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect("user:new")
    form = LoginForm()
    return render(request, "user/index.html", {'form': form})


def logins(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect(reverse("predictor:index"))
        else:
            messages.info(request, "Username OR Password is incorrect")
    return redirect(reverse("user:index"))

def logouts(request):
    logout(request)
    return redirect(reverse("user:index"))

def new(request):
    form = RegisterForm()
    return render(request, "user/new.html", {'form': form})


def create(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            messages.error(request, "Invalid user credentials")
    return redirect(reverse("user:new"))

apps/predictor/templates/predictor/index.html
{% extends 'user/base.html' %}
{% block title %} Dashboard{% endblock %}
{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'predictor/css/index.css' %}">
    <script src="{% static 'predictor/script/index.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
    <img class="navigation" onclick="setDisplay()" src="{% static 'predictor/images/icon2.png' %}" alt="ROCKET_SHIP">
    <div class="message2user fixed"></div>
    <div class="main-info">
        <div class="info-images">
            <img class="image-one" src="{% static 'predictor/images/brain_grid.png' %}" alt="">
            <img class="image-two" src="{% static 'predictor/images/human_grid.png' %}" alt="">
            <img class="image-three" src="{% static 'predictor/images/shuttle_grid.png' %}" alt="">
        </div>
        <div class="slide slide-one">
            <h1>WHAT IS MACHINE LEARNING?</h1>
            <div class="info slide-one-info">
                <p>Machine leanrning is the use of algorithms and statistics to find patterns in data.</p>
            </div>
        </div>
        <div class="slide slide-two">
            <h1>HOW IS IT APPLIED?</h1>
            <div class="info slide-two-info">
                <p>From Netflix to Instagram, algorithms utilize User data and browsing history to suggest television shows and movies, or advertisements and posts.</p>
            </div>
        </div>
        <div class="slide slide-three">
            <h1>WHAT IS THE FUTURE FOR AI?</h1>
            <div class="info slide-three-info">
                <p>Robotic bees will soon pollinate flowers around the world, and diagnosing patient illness may be removed from human error.</p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class="fixed background-text hide-toggle">
        <p>import pandas as pd</p>
        <p>import numpy as np</p>
        <p>import sklearn</p>
        <p>from sklearn import linear_model</p>
        <br>
        <p>def predictor(files, first, second, third, size, separator):</p>
        <p class="indentOne">data = pd.read_csv(files, sep=separator)</p>
        <p class="indentOne">data = data[["G1", "G2", "G3", first, second, third]]</p>
        <p class="indentOne">predict = "G3"</p>
        <p class="indentOne">x = np.array(data.drop([predict], 1))</p>
        <p class="indentOne">x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=float(size))</p>
        <p class="indentOne">linear = linear_model.LinearRegression()</p>
        <p class="indentOne">linear.fit(x_train, y_train)</p>
        <p class="indentOne">accuracy = linear.score(x_test, y_test)</p>
        <p class="indentOne">print('Accuracy: ', accuracy)</p>
        <p class="indentOne">print('Coefficient: \n', linear.coef_)</p>
        <p class="indentOne">print('Intercept: \n', linear.intercept_)</p>
        <p class="indentOne">predictions = linear.predict(x_test)</p>
        <p class="indentOne">results = {</p>
        <p class="indentTwo">"accuracy": accuracy, </p>
        <p class="indentTwo">"coefficient": linear.coef_, </p>
        <p class="indentTwo">"intercept": linear.intercept_,</p>
        <p class="indentTwo">"predictions": predictions, </p>
        <p class="indentTwo">"test": x_test, </p>
        <p class="indentTwo">"predicted": y_test,</p>
        <p class="indentOne">}</p>
        <br>
        <p class="indentOne">return results</p>
    </div>
    <div class="menu">
        <div class="background-text">
            <p>from django.conf.urls import url</p>
            <p>from . import views</p>
        </div>
        <br>
        <p>app_name = "navigation menu"</p>
        <br>
        <p>urlpatterns = [</p>
        <a class="indentOne displayNewToggle" href="{% url 'predictor:new' %}">url(r'^new$', views.new, name="new predicion"),</a>
        <br>
        <a class="indentOne displayLogoutToggle" href="{% url 'user:logouts' %}">url(r'^logout$', views.show, name="logout user"),</a>
    </div>
    <br>
    <div class="url-new">
        <p>def create(request):</p>
        <p class="indentOne">if request.method == "POST":</p>
        <p class="indentTwo">form = LearnForm(request.POST, request.FILES)</p>
        <br>
        <p class="indentTwo">if form.is_valid():</p>
        <p class="indentThree">prediction = predictor(request.FILES['file'], request.POST['first'], request.POST['second'], request.POST['third'], request.POST['size'], request.POST['separator'])</p>
        <p class="indentThree">return show(request, prediction)</p>
        <br>
        <p class="indentOne">return redirect(reverse("predictor:new")) </p> 
    </div>
    <div class="url-logout">
        <p>def logins(request):</p>
        <p class="indentOne">if request.method == 'POST':</p>
        <p class="indentTwo">username = request.POST['username']</p>
        <p class="indentTwo">password = request.POST['password1']</p>
        <br>
        <p class="indentTwo">user = authenticate(request, username=username, password=password)</p>
        <br>
        <p class="indentTwo">if user is not None:</p>
        <p class="indentThree">login(request, user)</p>
        <p class="indentThree">return redirect(reverse("predictor:index"))</p>
        <p class="indentTwo">else:</p>
        <p class="indentThree">rmessages.info(request, "Username OR Password is incorrect")</p>
        <p class="indentOne">return redirect(reverse("user:index"))</p>
        <br>
        <p>def logouts(request):</p>
        <p class="indentOne">logout(request)</p>
        <p class="indentOne">return redirect(reverse("user:index"))</p>
    </div>
</body>
{% endblock %}

apps/predictor/templates/predictor/new.html
{% extends 'user/base.html' %}
{% block title %} Load Data{% endblock %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'predictor/css/new.css' %}">
    <script src="{% static 'predictor/script/new.js' %}"></script>
</head>
<style>
</style>
<div class="message2user fixed"></div>
<br>
<br>
<br>
<br>
<div class="create-form fixed">
    <form action="{% url 'predictor:create' %}" method="POST" enctype="multipart/form-data" id="predictor_form">     
        {% csrf_token %}
            <p>file_name = "{{form.name}}"</p>
            <p class="indentOne">CSV_file = {{form.file}}</p>
            <p class="indentOne">test_size = "{{form.size}}"</p>
            <p class="indentOne">data_parameters = [</p>
            <p class="indentTwo">"{{form.first}}", "{{form.second}}", "{{form.third}}"</p>
            <p class="indentOne">]</p>
            <p class="indentOne">separator = {{form.separator}}</p>
            <p><input type="submit" value="Predict"><p>
    </form>
    <br>
    <div class="linear-regression-model">
        <p>linear_regression_model = {</p>
        <p class="indentOne"><span class="accuracy-toggle">"accuracy": {{data.accuracy}}</span></p>
        <p class="indentOne"><span class="coefficient-toggle">"coefficient": {{data.coefficient}}</span></p>
        <p class="indentOne"><span class="intercept-toggle"><span>"intercept": {{data.intercept}}</span></p>
        <p>}</p>
    </div>
</div>
<div class="data-results">
    <p class="right-align">TEST DATA / PREDICTION / RESULT</p>
</div>
<a href="{% url 'predictor:index' %}"><img class="navigation" onclick="setDisplay()" src="{% static 'predictor/images/icon2.png' %}" alt=""></a>
{% endblock %}

apps/predictor/templates/predictor/show.html
{% extends 'user/base.html' %}
{% block title %} Prediction{% endblock %}
{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'predictor/css/show.css' %}">
    <script src="{% static 'predictor/script/show.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<div class="message2user fixed"></div>
<br>
<br>
<br>
<br>
<div class="create-form-info fixed">
    <div class="form-info">
        <p>file_name = "{{info.name}}"</p>
        <p class="indentOne">CSV_file = "PLACEHOLDER"</p>  
        <p class="indentOne">test_size = "{{info.size}}"</p>
        <p class="indentOne">data_parameters = [</p>
        <p class="indentTwo">"{{info.first}}", "{{info.second}}", "{{info.third}}"</p>
        <p class="indentOne">]</p>
        <p class="indentOne">separator = "{{info.separator}}"</p>
        <br>
    </div>
    <br>
    <div class="linear-regression-model">
        <p>linear_regression_model = {</p>
        <p class="indentOne"><span class="accuracy-toggle">"accuracy": {{data.accuracy}}</span></p>
        <p class="indentOne"><span class="coefficient-toggle">"coefficient": {{data.coefficient}}</span></p>
        <p class="indentOne"><span class="intercept-toggle"><span>"intercept": {{data.intercept}}</span></p>
        <p>}</p>
    </div>
    <br>
    <div class="accuracy-info">
        <p>Accuracy is a measure of the closeness between a linear regressions computed result, and the true result given.</p>
        <p></p>
    </div>
    <div class="coefficient-info">
        <p>Coefficients are the values that multiply the predictor values. </p>
    </div>
    <div class="intercept-info">
        <p>Intercepts are where the line touches the axis so y intercept would cross the y axis and the x intercept would cross the x axis.</p>
    </div>
</div>

<div class="data-results">
    <p class="right-align">TEST DATA / PREDICTION / RESULT</p>
</div>

<div class="results">
    <table>
            {% for prediction in data.predictions %}
            {% for test in data.test %}
            {% for result in data.predicted %}
            <tr class="zoom">
                    <td class="first-column">{{forloop.counter}}{{test}}</td>
                    <td>{{forloop.counter}}{{prediction}}</td>
                    <td class="third-column"> {{forloop.counter}}{{result}}</td>
            </tr>
            {% endfor %}
            {% endfor %}
            {% endfor %}
    </table>
</div>
<a href="{% url 'predictor:new' %}"><img class="navigation" onclick="setDisplay()" src="{% static 'predictor/images/icon2.png' %}" alt=""></a>


{% endblock %}

apps/user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Learner-X: {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/base.css' %}">
</head>

<body>
    <div class="container" id="content">
        <header>
            <h1>LEARNERχ</h1>
        </header>
        <div class="content">
            <br>
            <br>
        {% block content %}
        {% endblock %}
        </div>
        <footer>
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                        {{ message }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </footer>
    </div>
</body>
</html>

apps/user/templates/user/index.html
{% extends 'user/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/index.css' %}">
    <script src="{% static 'user/script/index.js' %}"></script>
</head>
<body>

    <p class="message2user"></p>

    <div class="activeForm">
        <p>class LoginForm(UserLoginForm):</p>
        <div class="activeForm">
            <p class="indentOne">class Meta:</p>
            <p class="indentTwo">model = User</p>
            <p class="indentOne">def __init__(self, *args, **kwargs):</p>
            <p class="indentTwo">super(LoginForm, self).__init__(*args, **kwargs)</p>
            <p class="indentTwo">self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})</p>
            <p class="indentTwo">self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'})</p>
            <p>
                <form action="{% url 'user:logins' %}" method="POST">
                    {% csrf_token %}
                    <span class="indentTwo"><input type="submit" value="Login"> = ["{{form.username}}", "{{form.password1}}"]</span>
                </form>
            </p>
        </div>
    <br>
        <p class="inactiveLink"><a href="{% url 'user:new' %}" class="inactiveLink">class RegisterForm(UserCreationForm):</a></p>
        <div class="inactiveForm">
            <p class="indentOne">first_name = forms.CharField(max_length=255)</p>
            <p class="indentOne">last_name = forms.CharField(max_length=255)</p>
            <p class="indentOne">email = forms.EmailField()</p>
            <br>
            <p class="indentOne">class Meta:</p>
            <p class="indentTwo"><input type="submit" disabled value="Register"> = [</p>
            <p class="indentThree">"<input type="text" placeholder="First Name" disabled id="inactiveFirstName">", </p>
            <p class="indentThree">"<input type="text" placeholder="Last Name" disabled id="inactiveLastName">",</p>
            <p class="indentThree">"<input type="text" placeholder="Username" disabled id="inactiveUsername">",</p>
            <p class="indentThree">"<input type="text" placeholder="Email" disabled id="inactiveEmail">",</p>
            <p class="indentThree">"<input type="text" placeholder="Password" disabled id="inactivePassword">",</p>
            <p class="indentThree">"<input type="text" placeholder="Confirm" disabled id="inactivePassword2">"</p>
            <p class="indentTwo">]</p>
        </div>
            <span></span>
</body>
{% endblock %}

apps/user/templates/user/new.html
{% extends 'user/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/new.css' %}">
    <script src="{% static 'user/script/new.js' %}"></script>
</head>

<body>
    <p class="message2user"></p>

    <p class="inactiveLink"><a href="{% url 'user:logins' %}" class="inactiveLink">class LoginForm(UserLoginForm):</a></p>
    <div class="inactiveForm">
        <p class="indentOne">class Meta:</p>
        <p class="indentTwo">model = User</p>
        <p class="indentOne">def __init__(self, *args, **kwargs):</p>
        <p class="indentTwo">super(LoginForm, self).__init__(*args, **kwargs)</p>
        <p class="indentTwo">self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})</p>
        <p class="indentTwo">self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'})</p>
        <p>
            <form action="{% url 'user:logins' %}" method="POST">
                <span class="indentTwo"><input type="submit" disabled value="Login"> = ["<input type="text" placeholder="Username" disabled id="inactiveUsername">", "<input type="text" placeholder="Password" disabled id="inactivePassword">"]</span>
            </form>
        </p>
    </div>
    <br>
    <p class="activeForm">class RegisterForm(UserCreationForm):</p>
    <div class="activeForm">
        <p class="indentOne">first_name = forms.CharField(max_length=255)</p>
        <p class="indentOne">last_name = forms.CharField(max_length=255)</p>
        <p class="indentOne">email = forms.EmailField()</p>
        <br>
        <p class="indentOne">class Meta:</p>
        <form action="{% url 'user:create' %}" method="POST">
            {% csrf_token %}
            <p class="indentTwo"><input type="submit" value="Register"> = [</p>
            <p class="indentThree">"{{form.first_name}}", </p>
            <p class="indentThree">"{{form.last_name}}",</p>
            <p class="indentThree">"{{form.username}}",</p>
            <p class="indentThree">"{{form.email}}",</p>
            <p class="indentThree">"{{form.password1}}",</p>
            <p class="indentThree">"{{form.password2}}"</p>
        </form>
        <p class="indentTwo">]</p>
    </div>
    <div class="messages">
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </div>
</body>
{% endblock %}